"""
doc_generator.py - Auto-generates summary.md for each archived repository
using Jinja2 templates and repository metadata from the GitHub API.
"""

import logging
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape

from src.main.config import STALE_DAYS, TEMPLATE_DIR

logger = logging.getLogger(__name__)

# Inline fallback template (used when no template file is found on disk)
_SUMMARY_TEMPLATE = """\
# Repository Archive Summary

| Field | Value |
|-------|-------|
| **Repository** | {{ repo_name }} |
| **URL** | {{ repo_url }} |
| **Description** | {{ description or "No description provided." }} |
| **Primary Language** | {{ primary_language or "N/A" }} |
| **Archive Date** | {{ archive_date }} |
| **Reason** | Inactive for more than {{ stale_days }} days |
| **Last Commit** | {{ last_commit_date or "Unknown" }} |

---

## Language Breakdown

{% if languages %}
| Language | Percentage |
|----------|-----------|
{% for lang, pct in language_percentages.items() -%}
| {{ lang }} | {{ "%.1f"|format(pct) }}% |
{% endfor %}
{% else %}
_No language data available._
{% endif %}

---

## Top Contributors (Top 5)

{% if contributors %}
| # | GitHub Login | Commits |
|---|-------------|---------|
{% for c in contributors -%}
| {{ loop.index }} | {{ c.login }} | {{ c.commits }} |
{% endfor %}
{% else %}
_No contributor data available._
{% endif %}

---

## Recent Commit History (Last 10)

{% if recent_commits %}
| Date | Author | Message |
|------|--------|---------|
{% for commit in recent_commits -%}
| {{ commit.date[:10] }} | {{ commit.author }} | {{ commit.message[:80] }} |
{% endfor %}
{% else %}
_No commit history available._
{% endif %}

---

*This summary was auto-generated by the Git Repository Archiver.*
"""


class DocGenerator:
    """Generates summary.md files for archived repositories."""

    def __init__(self, template_dir: str = TEMPLATE_DIR):
        self._env = self._build_jinja_env(template_dir)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_summary(
        self,
        *,
        repo_name: str,
        repo_url: str,
        description: Optional[str],
        primary_language: Optional[str],
        languages: Dict[str, int],
        contributors: List[Dict],
        recent_commits: List[Dict],
        last_commit_date: Optional[str],
        output_path: str,
    ) -> str:
        """
        Render summary.md and write it to output_path.

        Returns:
            The full path to the generated file.
        """
        now_utc = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        # Build language percentage map
        total_bytes = sum(languages.values()) or 1
        language_percentages = {
            lang: (bytes_ / total_bytes) * 100
            for lang, bytes_ in sorted(
                languages.items(), key=lambda x: x[1], reverse=True
            )
        }

        context = {
            "repo_name": repo_name,
            "repo_url": repo_url,
            "description": description,
            "primary_language": primary_language,
            "languages": languages,
            "language_percentages": language_percentages,
            "contributors": contributors,
            "recent_commits": recent_commits,
            "last_commit_date": last_commit_date,
            "archive_date": now_utc,
            "stale_days": STALE_DAYS,
        }

        try:
            template = self._env.get_template("summary.md.j2")
            rendered = template.render(**context)
        except Exception:
            # Fall back to inline template
            template = self._env.from_string(_SUMMARY_TEMPLATE)
            rendered = template.render(**context)

        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(rendered)

        logger.info("summary.md written to '%s'.", output_path)
        return output_path

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_jinja_env(template_dir: str) -> Environment:
        loaders: list = []
        if os.path.isdir(template_dir):
            loaders.append(FileSystemLoader(template_dir))

        if loaders:
            from jinja2 import ChoiceLoader

            env = Environment(
                loader=ChoiceLoader(loaders),
                autoescape=select_autoescape(enabled_extensions=()),
                trim_blocks=True,
                lstrip_blocks=True,
            )
        else:
            env = Environment(
                loader=None,
                autoescape=False,
                trim_blocks=True,
                lstrip_blocks=True,
            )
        return env
